// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCqGSmlRYFA2722bomrHflIaRLK6wfck8',
    appId: '1:176885556645:android:302c7f170fdf0d73a9b44c',
    messagingSenderId: '176885556645',
    projectId: 'blood-69457',
    storageBucket: 'blood-69457.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABnea1rU2qjZG52gQ5p4sH9rHZ85FttTs',
    appId: '1:176885556645:ios:c706aeccc85cbd9ea9b44c',
    messagingSenderId: '176885556645',
    projectId: 'blood-69457',
    storageBucket: 'blood-69457.firebasestorage.app',
    iosBundleId: 'com.example.blood2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABnea1rU2qjZG52gQ5p4sH9rHZ85FttTs',
    appId: '1:176885556645:ios:c706aeccc85cbd9ea9b44c',
    messagingSenderId: '176885556645',
    projectId: 'blood-69457',
    storageBucket: 'blood-69457.firebasestorage.app',
    iosBundleId: 'com.example.blood2',
  );
}
